# Generated by Django 4.2.7 on 2023-11-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0002_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charger',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
