# Generated by Django 4.2.7 on 2023-11-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_auth_status_user_phone_user_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('new', 'new'), ('code', 'code'), ('registered', 'registered')], default='new', max_length=31),
        ),
    ]
