# Generated by Django 4.2.7 on 2023-11-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('playlist_id', models.IntegerField()),
                ('title', models.CharField(max_length=221)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='playlists/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
